version: '3.8'

services:
  web:
    build: .
    container_name: iw_parcial_pregunta10
    ports:
      - "8089:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: iw_parcial_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petclinic
      MYSQL_USER: pc
      MYSQL_PASSWORD: pc
    volumes:
      - db_data:/var/lib/mysql
      - ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
